/**
 * Achievement configurations for different roles
 * Each achievement has triggers and conditions
 */

const DONOR_ACHIEVEMENTS = [
  {
    id: 'first_donation',
    title: 'First Donation',
    description: 'Made your first donation',
    icon: '🎉',
    pointsAwarded: 25,
    trigger: 'DONATION_COUNT',
    targetValue: 1,
    type: 'MILESTONE',
  },
  {
    id: 'generous_soul',
    title: 'Generous Soul',
    description: 'Donated 5 times',
    icon: '❤️',
    pointsAwarded: 50,
    trigger: 'DONATION_COUNT',
    targetValue: 5,
    type: 'MILESTONE',
  },
  {
    id: 'food_champion',
    title: 'Food Champion',
    description: 'Donated 10 times',
    icon: '🏆',
    pointsAwarded: 100,
    trigger: 'DONATION_COUNT',
    targetValue: 10,
    type: 'MILESTONE',
  },
  {
    id: 'impact_leader',
    title: 'Impact Leader',
    description: 'Donated 25 times',
    icon: '👑',
    pointsAwarded: 250,
    trigger: 'DONATION_COUNT',
    targetValue: 25,
    type: 'MILESTONE',
  },
  {
    id: 'daily_donor',
    title: 'Daily Donor',
    description: 'Donated on 7 consecutive days',
    icon: '📅',
    pointsAwarded: 75,
    trigger: 'CONSECUTIVE_DAYS',
    targetValue: 7,
    type: 'STREAK',
  },
  {
    id: 'variety_is_life',
    title: 'Variety is Life',
    description: 'Donated all 9 food types',
    icon: '🌈',
    pointsAwarded: 150,
    trigger: 'FOOD_TYPE_VARIETY',
    targetValue: 9,
    type: 'SPECIAL',
  },
  {
    id: 'bulk_donor',
    title: 'Bulk Donor',
    description: 'Donated 100+ kg of food',
    icon: '📦',
    pointsAwarded: 200,
    trigger: 'TOTAL_QUANTITY',
    targetValue: 100,
    type: 'MILESTONE',
  },
];

const NGO_ACHIEVEMENTS = [
  {
    id: 'first_collection',
    title: 'First Collection',
    description: 'Accepted your first donation',
    icon: '🎯',
    pointsAwarded: 25,
    trigger: 'COLLECTION_COUNT',
    targetValue: 1,
    type: 'MILESTONE',
  },
  {
    id: 'relief_worker',
    title: 'Relief Worker',
    description: 'Collected 5 donations',
    icon: '🤝',
    pointsAwarded: 50,
    trigger: 'COLLECTION_COUNT',
    targetValue: 5,
    type: 'MILESTONE',
  },
  {
    id: 'community_guardian',
    title: 'Community Guardian',
    description: 'Collected 10 donations',
    icon: '🛡️',
    pointsAwarded: 100,
    trigger: 'COLLECTION_COUNT',
    targetValue: 10,
    type: 'MILESTONE',
  },
  {
    id: 'hero',
    title: 'Hero',
    description: 'Collected 25 donations',
    icon: '🦸',
    pointsAwarded: 250,
    trigger: 'COLLECTION_COUNT',
    targetValue: 25,
    type: 'MILESTONE',
  },
  {
    id: 'daily_hero',
    title: 'Daily Hero',
    description: 'Collected donations on 7 consecutive days',
    icon: '⭐',
    pointsAwarded: 75,
    trigger: 'CONSECUTIVE_DAYS',
    targetValue: 7,
    type: 'STREAK',
  },
  {
    id: 'food_bank_master',
    title: 'Food Bank Master',
    description: 'Collected 1000+ kg of food',
    icon: '🏪',
    pointsAwarded: 300,
    trigger: 'TOTAL_QUANTITY',
    targetValue: 1000,
    type: 'MILESTONE',
  },
  {
    id: 'fast_responder',
    title: 'Fast Responder',
    description: 'Accepted donation within 30 minutes',
    icon: '⚡',
    pointsAwarded: 40,
    trigger: 'RESPONSE_TIME',
    targetValue: 30,
    type: 'SPECIAL',
  },
];

const VOLUNTEER_ACHIEVEMENTS = [
  {
    id: 'first_delivery',
    title: 'First Delivery',
    description: 'Completed your first delivery',
    icon: '🚀',
    pointsAwarded: 25,
    trigger: 'PICKUP_COUNT',
    targetValue: 1,
    type: 'MILESTONE',
  },
  {
    id: 'delivery_expert',
    title: 'Delivery Expert',
    description: 'Completed 5 deliveries',
    icon: '📦',
    pointsAwarded: 50,
    trigger: 'PICKUP_COUNT',
    targetValue: 5,
    type: 'MILESTONE',
  },
  {
    id: 'logistics_master',
    title: 'Logistics Master',
    description: 'Completed 10 deliveries',
    icon: '🚛',
    pointsAwarded: 100,
    trigger: 'PICKUP_COUNT',
    targetValue: 10,
    type: 'MILESTONE',
  },
  {
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Completed 25 deliveries',
    icon: '💪',
    pointsAwarded: 250,
    trigger: 'PICKUP_COUNT',
    targetValue: 25,
    type: 'MILESTONE',
  },
  {
    id: 'daily_driver',
    title: 'Daily Driver',
    description: 'Delivered on 7 consecutive days',
    icon: '🌅',
    pointsAwarded: 75,
    trigger: 'CONSECUTIVE_DAYS',
    targetValue: 7,
    type: 'STREAK',
  },
  {
    id: 'speed_demon',
    title: 'Speed Demon',
    description: 'Completed delivery in under 1 hour',
    icon: '🏎️',
    pointsAwarded: 40,
    trigger: 'DELIVERY_TIME',
    targetValue: 60,
    type: 'SPECIAL',
  },
  {
    id: 'eco_warrior',
    title: 'Eco Warrior',
    description: 'Delivered 500+ kg of food',
    icon: '🌱',
    pointsAwarded: 200,
    trigger: 'TOTAL_QUANTITY',
    targetValue: 500,
    type: 'MILESTONE',
  },
  {
    id: 'never_late',
    title: 'Never Late',
    description: 'Completed 10 deliveries on time',
    icon: '✅',
    pointsAwarded: 150,
    trigger: 'ON_TIME_DELIVERIES',
    targetValue: 10,
    type: 'SPECIAL',
  },
];

/**
 * Badge configurations
 */
const BADGES = {
  BRONZE: {
    name: 'Bronze Badge',
    description: 'Achieve 100 total points',
    pointsRequired: 100,
    icon: '🥉',
  },
  SILVER: {
    name: 'Silver Badge',
    description: 'Achieve 500 total points',
    pointsRequired: 500,
    icon: '🥈',
  },
  GOLD: {
    name: 'Gold Badge',
    description: 'Achieve 1000 total points',
    pointsRequired: 1000,
    icon: '🥇',
  },
  PLATINUM: {
    name: 'Platinum Badge',
    description: 'Achieve 2500 total points',
    pointsRequired: 2500,
    icon: '💎',
  },
  DIAMOND: {
    name: 'Diamond Badge',
    description: 'Achieve 5000 total points',
    pointsRequired: 5000,
    icon: '👑',
  },
  SPECIAL: {
    name: 'Special Badge',
    description: 'Unlock a special achievement',
    pointsRequired: 0,
    icon: '⭐',
  },
};

module.exports = {
  DONOR_ACHIEVEMENTS,
  NGO_ACHIEVEMENTS,
  VOLUNTEER_ACHIEVEMENTS,
  BADGES,
};
